artifact_uri: file:///Users/omprakashgunja/Documents/GitHub/AI-Experiments-2025/AI-Experiments-2025/mlruns/0/969df77b54ba4be987fd20d32e7aa7be/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 969df77b54ba4be987fd20d32e7aa7be
run_name: caring-rook-765
run_uuid: 969df77b54ba4be987fd20d32e7aa7be
source_name: ''
source_type: 4
source_version: ''
start_time: 1739060065270
status: 1
tags: []
user_id: omprakashgunja
