artifact_location: file:///Users/omprakashgunja/Documents/GitHub/AI-Experiments-2025/AI-Experiments-2025/mlruns/0
creation_time: 1739032448309
experiment_id: '0'
last_update_time: 1739032448309
lifecycle_stage: active
name: Default
