artifact_uri: file:///Users/omprakashgunja/Documents/GitHub/AI-Experiments-2025/AI-Experiments-2025/mlruns/0/f1965101bf074593925a4dc6d7bc74cf/artifacts
end_time: 1739032468877
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f1965101bf074593925a4dc6d7bc74cf
run_name: exultant-hen-727
run_uuid: f1965101bf074593925a4dc6d7bc74cf
source_name: ''
source_type: 4
source_version: ''
start_time: 1739032448644
status: 3
tags: []
user_id: omprakashgunja
