artifact_uri: file:///Users/omprakashgunja/Documents/GitHub/AI-Experiments-2025/AI-Experiments-2025/mlruns/0/7750a456535e4486b11b9beba25ad294/artifacts
end_time: 1739033413053
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7750a456535e4486b11b9beba25ad294
run_name: bald-slug-823
run_uuid: 7750a456535e4486b11b9beba25ad294
source_name: ''
source_type: 4
source_version: ''
start_time: 1739033306835
status: 3
tags: []
user_id: omprakashgunja
